Attribute VB_Name = "GLOBALS"
Public UseDataBase As Boolean
Public NetCashFile As String
Public UserLogon As Boolean
Public UserProfile As Integer
Public UserName As String

Public ERROR_SESSION_MESSAGE As String
Public PRODUCT_NAME As String

Public DateStart As String
Public DateEnd As String
Public bReportAll As Boolean

Public bROOT As Boolean

Public PRINTER_TICKET As Boolean

Public TYPE_REPORT_ZX As String


